spring:
  application:
    name: web_service

  datasource:
    url: jdbc:postgresql://dpg-d9dfr1ernols73cbelu0-a.singapore-postgres.render.com:5432/food_delivery_app_96bo
    username: food_delivery_app_96bo_user
    password: txRysP8S2eRnJTaTYLgGDR1755u9uLIt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080